/* ===================================================================
   forca-words.js — Banco de 301 palavras do jogo da forca (cela)
   Organizadas da mais fácil para a mais difícil.
   Define window.FORCA_WORDS, consumido por js/forca-app.js
   =================================================================== */

(function () {
  "use strict";

  window.FORCA_WORDS = [
    { id: 1, word: "SOL", hint: "Estrela que ilumina a Terra durante o dia" },
    { id: 2, word: "LUA", hint: "Satélite natural da Terra" },
    { id: 3, word: "MAR", hint: "Grande extensão de água salgada" },
    { id: 4, word: "PAO", hint: "Alimento feito de farinha de trigo, comum no café da manhã" },
    { id: 5, word: "GATO", hint: "Animal doméstico que mia" },
    { id: 6, word: "CAO", hint: "O melhor amigo do homem" },
    { id: 7, word: "CASA", hint: "Lugar onde se mora" },
    { id: 8, word: "BOLA", hint: "Objeto redondo usado em vários esportes" },
    { id: 9, word: "MESA", hint: "Móvel usado para refeições ou trabalho" },
    { id: 10, word: "LIVRO", hint: "Objeto com páginas usado para leitura" },
    { id: 11, word: "FLOR", hint: "Parte colorida e perfumada de uma planta" },
    { id: 12, word: "AGUA", hint: "Líquido essencial para a vida" },
    { id: 13, word: "FOGO", hint: "Chama usada para cozinhar ou aquecer" },
    { id: 14, word: "TERRA", hint: "Planeta em que vivemos" },
    { id: 15, word: "CEU", hint: "Onde ficam as nuvens e as estrelas" },
    { id: 16, word: "CHUVA", hint: "Água que cai das nuvens" },
    { id: 17, word: "VENTO", hint: "Ar em movimento" },
    { id: 18, word: "NUVEM", hint: "Massa branca ou cinza que flutua no céu" },
    { id: 19, word: "PRAIA", hint: "Faixa de areia à beira-mar" },
    { id: 20, word: "RIO", hint: "Curso de água que corre até o mar" },
    { id: 21, word: "LAGO", hint: "Grande extensão de água cercada por terra" },
    { id: 22, word: "ARVORE", hint: "Planta grande com tronco, galhos e folhas" },
    { id: 23, word: "FOLHA", hint: "Parte verde de uma planta" },
    { id: 24, word: "FRUTA", hint: "Parte comestível e doce de uma planta" },
    { id: 25, word: "MACA", hint: "Fruta vermelha ou verde, redonda" },
    { id: 26, word: "BANANA", hint: "Fruta amarela e alongada" },
    { id: 27, word: "UVA", hint: "Fruta pequena e redonda, usada para fazer vinho" },
    { id: 28, word: "LEITE", hint: "Bebida branca que vem da vaca" },
    { id: 29, word: "QUEIJO", hint: "Alimento feito a partir do leite" },
    { id: 30, word: "OVO", hint: "Alimento posto pela galinha" },
    { id: 31, word: "ARROZ", hint: "Grão branco muito consumido no Brasil" },
    { id: 32, word: "CARNE", hint: "Alimento de origem animal" },
    { id: 33, word: "PEIXE", hint: "Animal que vive na água e tem guelras" },
    { id: 34, word: "GALINHA", hint: "Ave que põe ovos" },
    { id: 35, word: "PATO", hint: "Ave aquática que faz 'quack'" },
    { id: 36, word: "PORCO", hint: "Animal de fazenda que faz 'oinc'" },
    { id: 37, word: "VACA", hint: "Animal que dá leite" },
    { id: 38, word: "CAVALO", hint: "Animal usado para montaria" },
    { id: 39, word: "COELHO", hint: "Animal de orelhas compridas que pula" },
    { id: 40, word: "RATO", hint: "Pequeno roedor" },
    { id: 41, word: "LEAO", hint: "Rei da selva" },
    { id: 42, word: "TIGRE", hint: "Felino grande com listras" },
    { id: 43, word: "URSO", hint: "Animal grande e peludo que hiberna" },
    { id: 44, word: "LOBO", hint: "Animal selvagem parecido com um cão grande" },
    { id: 45, word: "COBRA", hint: "Réptil sem pernas" },
    { id: 46, word: "SAPO", hint: "Anfíbio que pula e coaxa" },
    { id: 47, word: "ABELHA", hint: "Inseto que produz mel" },
    { id: 48, word: "FORMIGA", hint: "Inseto pequeno que vive em colônias" },
    { id: 49, word: "ARANHA", hint: "Animal de oito patas que tece teias" },
    { id: 50, word: "PASSARO", hint: "Animal que voa e tem penas" },
    { id: 51, word: "BOLO", hint: "Doce assado no forno, comum em aniversários" },
    { id: 52, word: "DOCE", hint: "Sabor de açúcar; sinônimo de guloseima" },
    { id: 53, word: "SORVETE", hint: "Sobremesa gelada e doce" },
    { id: 54, word: "PIZZA", hint: "Prato italiano redondo com queijo e molho" },
    { id: 55, word: "ESCOLA", hint: "Lugar onde se estuda" },
    { id: 56, word: "CADERNO", hint: "Objeto usado para escrever nas aulas" },
    { id: 57, word: "LAPIS", hint: "Instrumento usado para escrever ou desenhar" },
    { id: 58, word: "CANETA", hint: "Instrumento de escrita com tinta" },
    { id: 59, word: "PORTA", hint: "Estrutura usada para entrar ou sair de um lugar" },
    { id: 60, word: "JANELA", hint: "Abertura na parede para entrada de luz" },
    { id: 61, word: "CADEIRA", hint: "Móvel usado para sentar" },
    { id: 62, word: "COMPUTADOR", hint: "Máquina usada para trabalhar, jogar e navegar na internet" },
    { id: 63, word: "TELEFONE", hint: "Aparelho usado para fazer ligações" },
    { id: 64, word: "TELEVISAO", hint: "Aparelho usado para assistir programas e filmes" },
    { id: 65, word: "GELADEIRA", hint: "Eletrodoméstico que mantém alimentos frios" },
    { id: 66, word: "FOGAO", hint: "Eletrodoméstico usado para cozinhar" },
    { id: 67, word: "BICICLETA", hint: "Veículo de duas rodas movido a pedal" },
    { id: 68, word: "CARRO", hint: "Veículo de quatro rodas usado para transporte" },
    { id: 69, word: "AVIAO", hint: "Veículo que voa e transporta passageiros" },
    { id: 70, word: "BARCO", hint: "Veículo usado para navegar na água" },
    { id: 71, word: "TREM", hint: "Veículo que anda sobre trilhos" },
    { id: 72, word: "ONIBUS", hint: "Veículo grande de transporte coletivo" },
    { id: 73, word: "MOTOCICLETA", hint: "Veículo de duas rodas com motor" },
    { id: 74, word: "HOSPITAL", hint: "Lugar onde pessoas doentes são tratadas" },
    { id: 75, word: "MEDICO", hint: "Profissional que cuida da saúde das pessoas" },
    { id: 76, word: "PROFESSOR", hint: "Profissional que ensina em uma escola" },
    { id: 77, word: "ENGENHEIRO", hint: "Profissional que projeta construções e estruturas" },
    { id: 78, word: "ADVOGADO", hint: "Profissional que atua na área jurídica" },
    { id: 79, word: "COZINHEIRO", hint: "Profissional que prepara comida" },
    { id: 80, word: "BOMBEIRO", hint: "Profissional que apaga incêndios e faz resgates" },
    { id: 81, word: "POLICIAL", hint: "Profissional que cuida da segurança pública" },
    { id: 82, word: "DENTISTA", hint: "Profissional que cuida dos dentes" },
    { id: 83, word: "PADEIRO", hint: "Profissional que faz pão" },
    { id: 84, word: "MONTANHA", hint: "Grande elevação natural do terreno" },
    { id: 85, word: "DESERTO", hint: "Região seca com pouca vegetação e chuva" },
    { id: 86, word: "FLORESTA", hint: "Área com muitas árvores" },
    { id: 87, word: "CACHOEIRA", hint: "Queda de água natural" },
    { id: 88, word: "VULCAO", hint: "Montanha que pode expelir lava" },
    { id: 89, word: "ILHA", hint: "Porção de terra cercada de água por todos os lados" },
    { id: 90, word: "CONTINENTE", hint: "Grande massa de terra, como a África ou a Ásia" },
    { id: 91, word: "OCEANO", hint: "Grande extensão de água salgada, maior que um mar" },
    { id: 92, word: "ESTRELA", hint: "Corpo celeste que brilha no céu à noite" },
    { id: 93, word: "PLANETA", hint: "Corpo celeste que orbita uma estrela" },
    { id: 94, word: "FOGUETE", hint: "Veículo usado para viajar ao espaço" },
    { id: 95, word: "ASTRONAUTA", hint: "Profissional que viaja ao espaço" },
    { id: 96, word: "GALAXIA", hint: "Enorme conjunto de estrelas, planetas e poeira cósmica" },
    { id: 97, word: "MUSICA", hint: "Arte de combinar sons de forma agradável" },
    { id: 98, word: "VIOLAO", hint: "Instrumento musical de cordas" },
    { id: 99, word: "PIANO", hint: "Instrumento musical de teclas" },
    { id: 100, word: "BATERIA", hint: "Instrumento musical de percussão com vários tambores" },
    { id: 101, word: "GUITARRA", hint: "Instrumento musical elétrico de cordas" },
    { id: 102, word: "FUTEBOL", hint: "Esporte jogado com os pés e uma bola redonda" },
    { id: 103, word: "BASQUETE", hint: "Esporte jogado com uma bola e uma cesta" },
    { id: 104, word: "NATACAO", hint: "Esporte praticado dentro d'água" },
    { id: 105, word: "VOLEIBOL", hint: "Esporte jogado com uma rede e uma bola, sem deixá-la cair" },
    { id: 106, word: "TENIS", hint: "Esporte jogado com raquete e uma bolinha" },
    { id: 107, word: "CORRIDA", hint: "Competição de velocidade a pé ou em veículos" },
    { id: 108, word: "NATUREZA", hint: "Conjunto de tudo que existe sem interferência humana" },
    { id: 109, word: "ANIVERSARIO", hint: "Data comemorativa do dia do nascimento" },
    { id: 110, word: "CASAMENTO", hint: "Cerimônia de união entre duas pessoas" },
    { id: 111, word: "FAMILIA", hint: "Grupo de pessoas unidas por parentesco" },
    { id: 112, word: "AMIZADE", hint: "Relação de afeto e confiança entre pessoas" },
    { id: 113, word: "VIAGEM", hint: "Deslocamento de um lugar para outro, geralmente para lazer" },
    { id: 114, word: "FERIAS", hint: "Período de descanso, geralmente sem trabalhar ou estudar" },
    { id: 115, word: "TRABALHO", hint: "Atividade realizada para ganhar dinheiro" },
    { id: 116, word: "DINHEIRO", hint: "Meio usado para comprar coisas" },
    { id: 117, word: "BANCO", hint: "Instituição que guarda e movimenta dinheiro" },
    { id: 118, word: "MERCADO", hint: "Lugar onde se compram alimentos e outros produtos" },
    { id: 119, word: "SHOPPING", hint: "Grande centro comercial com várias lojas" },
    { id: 120, word: "RESTAURANTE", hint: "Estabelecimento onde se compram refeições prontas" },
    { id: 121, word: "HOTEL", hint: "Estabelecimento onde viajantes se hospedam" },
    { id: 122, word: "CORACAO", hint: "Órgão que bombeia sangue pelo corpo" },
    { id: 123, word: "CEREBRO", hint: "Órgão responsável pelos pensamentos e comandos do corpo" },
    { id: 124, word: "PULMAO", hint: "Órgão usado para respirar" },
    { id: 125, word: "ESQUELETO", hint: "Estrutura de ossos do corpo" },
    { id: 126, word: "MUSCULO", hint: "Tecido do corpo responsável pelo movimento" },
    { id: 127, word: "VITAMINA", hint: "Substância essencial encontrada em alimentos, importante para a saúde" },
    { id: 128, word: "BACTERIA", hint: "Microrganismo unicelular, pode causar doenças ou ser benéfico" },
    { id: 129, word: "VACINA", hint: "Substância que protege o corpo contra doenças" },
    { id: 130, word: "REMEDIO", hint: "Substância usada para tratar doenças" },
    { id: 131, word: "CIRURGIA", hint: "Procedimento médico realizado para tratar o corpo" },
    { id: 132, word: "GRAVIDADE", hint: "Força que atrai os corpos para o centro da Terra" },
    { id: 133, word: "ELETRICIDADE", hint: "Forma de energia usada para acender lâmpadas e ligar aparelhos" },
    { id: 134, word: "MAGNETISMO", hint: "Força de atração ou repulsão entre certos materiais" },
    { id: 135, word: "TEMPERATURA", hint: "Medida do calor ou frio de algo" },
    { id: 136, word: "PRESSAO", hint: "Força exercida sobre uma superfície" },
    { id: 137, word: "VELOCIDADE", hint: "Medida de quão rápido algo se move" },
    { id: 138, word: "ENERGIA", hint: "Capacidade de realizar trabalho ou movimento" },
    { id: 139, word: "COMBUSTIVEL", hint: "Substância usada para gerar energia, como a gasolina" },
    { id: 140, word: "RECICLAGEM", hint: "Processo de transformar lixo em novos materiais" },
    { id: 141, word: "POLUICAO", hint: "Contaminação do ambiente por resíduos ou substâncias nocivas" },
    { id: 142, word: "BIODIVERSIDADE", hint: "Variedade de espécies de seres vivos em um ambiente" },
    { id: 143, word: "ECOSSISTEMA", hint: "Conjunto de seres vivos e o ambiente onde interagem" },
    { id: 144, word: "ATMOSFERA", hint: "Camada de gases que envolve um planeta" },
    { id: 145, word: "FOTOSSINTESE", hint: "Processo pelo qual as plantas produzem seu próprio alimento" },
    { id: 146, word: "EVOLUCAO", hint: "Processo de mudança gradual das espécies ao longo do tempo" },
    { id: 147, word: "DINOSSAURO", hint: "Réptil gigante que viveu há milhões de anos" },
    { id: 148, word: "FOSSIL", hint: "Restos preservados de seres vivos muito antigos" },
    { id: 149, word: "METEORO", hint: "Corpo celeste que cruza a atmosfera terrestre e brilha" },
    { id: 150, word: "COMETA", hint: "Corpo celeste com uma cauda visível, formado por gelo e poeira" },
    { id: 151, word: "ECLIPSE", hint: "Fenômeno em que um corpo celeste encobre outro" },
    { id: 152, word: "CONSTELACAO", hint: "Conjunto de estrelas que formam um padrão reconhecível no céu" },
    { id: 153, word: "UNIVERSO", hint: "Tudo que existe: espaço, tempo, matéria e energia" },
    { id: 154, word: "DEMOCRACIA", hint: "Sistema de governo baseado na participação do povo" },
    { id: 155, word: "CONSTITUICAO", hint: "Lei máxima que organiza um país" },
    { id: 156, word: "ELEICAO", hint: "Processo de escolha de representantes pelo voto" },
    { id: 157, word: "CIDADANIA", hint: "Conjunto de direitos e deveres de quem vive em um país" },
    { id: 158, word: "ECONOMIA", hint: "Estudo da produção, distribuição e consumo de bens" },
    { id: 159, word: "INFLACAO", hint: "Aumento generalizado dos preços em um país" },
    { id: 160, word: "INVESTIMENTO", hint: "Aplicação de dinheiro visando retorno futuro" },
    { id: 161, word: "EMPREENDEDOR", hint: "Pessoa que cria e gerencia seu próprio negócio" },
    { id: 162, word: "TECNOLOGIA", hint: "Conjunto de conhecimentos aplicados para criar ferramentas e soluções" },
    { id: 163, word: "INTERNET", hint: "Rede mundial que conecta computadores" },
    { id: 164, word: "APLICATIVO", hint: "Programa usado em celulares e computadores" },
    { id: 165, word: "ALGORITMO", hint: "Sequência de passos para resolver um problema" },
    { id: 166, word: "INTELIGENCIA", hint: "Capacidade de aprender, entender e resolver problemas" },
    { id: 167, word: "ROBOTICA", hint: "Área que estuda a criação de máquinas automatizadas" },
    { id: 168, word: "ARQUITETURA", hint: "Arte e técnica de projetar edifícios" },
    { id: 169, word: "ENGENHARIA", hint: "Área que aplica ciência para criar soluções técnicas" },
    { id: 170, word: "FILOSOFIA", hint: "Estudo das questões fundamentais sobre existência e conhecimento" },
    { id: 171, word: "PSICOLOGIA", hint: "Estudo da mente e do comportamento humano" },
    { id: 172, word: "SOCIOLOGIA", hint: "Estudo da sociedade e das relações humanas" },
    { id: 173, word: "LITERATURA", hint: "Arte de escrever textos, como romances e poemas" },
    { id: 174, word: "POESIA", hint: "Forma de escrita com ritmo e, muitas vezes, rimas" },
    { id: 175, word: "ROMANCE", hint: "Obra literária de ficção, geralmente longa" },
    { id: 176, word: "TEATRO", hint: "Arte de representar histórias ao vivo para uma plateia" },
    { id: 177, word: "ESCULTURA", hint: "Arte de criar formas tridimensionais em materiais como pedra ou metal" },
    { id: 178, word: "PINTURA", hint: "Arte de criar imagens usando tintas" },
    { id: 179, word: "FOTOGRAFIA", hint: "Arte de capturar imagens através de uma câmera" },
    { id: 180, word: "CINEMA", hint: "Arte de contar histórias através de filmes" },
    { id: 181, word: "ARQUEOLOGIA", hint: "Estudo de civilizações antigas através de seus vestígios" },
    { id: 182, word: "HIPOTESE", hint: "Suposição que precisa ser testada para virar teoria" },
    { id: 183, word: "PARADIGMA", hint: "Modelo ou padrão de pensamento amplamente aceito" },
    { id: 184, word: "METAFORA", hint: "Figura de linguagem que compara sem usar 'como'" },
    { id: 185, word: "IRONIA", hint: "Figura de linguagem que expressa o contrário do que se diz" },
    { id: 186, word: "SARCASMO", hint: "Forma de ironia usada para zombar ou criticar" },
    { id: 187, word: "AMBIGUIDADE", hint: "Qualidade do que pode ter mais de um significado" },
    { id: 188, word: "CONTROVERSIA", hint: "Discussão pública sobre um tema polêmico" },
    { id: 189, word: "BUROCRACIA", hint: "Conjunto de normas e procedimentos administrativos, às vezes excessivos" },
    { id: 190, word: "DIPLOMACIA", hint: "Arte de negociar relações entre países" },
    { id: 191, word: "SOBERANIA", hint: "Poder supremo de um Estado sobre seu território" },
    { id: 192, word: "COLONIZACAO", hint: "Processo histórico de ocupação de um território por outro povo" },
    { id: 193, word: "INDEPENDENCIA", hint: "Estado de não depender de outro país ou poder" },
    { id: 194, word: "REVOLUCAO", hint: "Mudança brusca e profunda em um sistema político ou social" },
    { id: 195, word: "MONARQUIA", hint: "Sistema de governo liderado por um rei ou rainha" },
    { id: 196, word: "REPUBLICA", hint: "Sistema de governo em que o poder vem do povo, sem monarca" },
    { id: 197, word: "FEDERACAO", hint: "União de estados ou províncias sob um governo central" },
    { id: 198, word: "GLOBALIZACAO", hint: "Processo de integração econômica e cultural entre países" },
    { id: 199, word: "SUSTENTABILIDADE", hint: "Capacidade de atender necessidades sem prejudicar o futuro" },
    { id: 200, word: "BIOTECNOLOGIA", hint: "Uso de organismos vivos para desenvolver produtos e tecnologias" },
    { id: 201, word: "NANOTECNOLOGIA", hint: "Ciência que manipula materiais em escala extremamente pequena" },
    { id: 202, word: "CRIPTOGRAFIA", hint: "Técnica de codificar informações para proteger dados" },
    { id: 203, word: "PROGRAMACAO", hint: "Processo de criar instruções para computadores" },
    { id: 204, word: "CIBERNETICA", hint: "Estudo de sistemas de controle e comunicação, humanos ou de máquinas" },
    { id: 205, word: "NEUROCIENCIA", hint: "Estudo científico do sistema nervoso e do cérebro" },
    { id: 206, word: "GENETICA", hint: "Estudo da hereditariedade e dos genes" },
    { id: 207, word: "MICROBIOLOGIA", hint: "Estudo dos microrganismos" },
    { id: 208, word: "ASTROFISICA", hint: "Ramo da física que estuda os astros e o universo" },
    { id: 209, word: "TERMODINAMICA", hint: "Ramo da física que estuda calor e energia" },
    { id: 210, word: "RELATIVIDADE", hint: "Teoria física de Einstein sobre espaço, tempo e gravidade" },
    { id: 211, word: "QUANTICA", hint: "Física que estuda partículas em escala subatômica" },
    { id: 212, word: "RADIOATIVIDADE", hint: "Emissão espontânea de radiação por certos átomos instáveis" },
    { id: 213, word: "MOLECULA", hint: "Menor unidade de uma substância que mantém suas propriedades" },
    { id: 214, word: "CROMOSSOMO", hint: "Estrutura que carrega os genes dentro das células" },
    { id: 215, word: "METABOLISMO", hint: "Conjunto de reações químicas que ocorrem no corpo" },
    { id: 216, word: "IMUNOLOGIA", hint: "Estudo do sistema de defesa do corpo" },
    { id: 217, word: "EPIDEMIOLOGIA", hint: "Estudo da distribuição e controle de doenças em populações" },
    { id: 218, word: "PANDEMIA", hint: "Doença que se espalha por vários países ou continentes" },
    { id: 219, word: "ANTIBIOTICO", hint: "Medicamento usado para combater infecções bacterianas" },
    { id: 220, word: "ANESTESIA", hint: "Procedimento médico que elimina a sensação de dor" },
    { id: 221, word: "FISIOTERAPIA", hint: "Tratamento que usa exercícios para recuperar movimentos do corpo" },
    { id: 222, word: "NUTRICIONISTA", hint: "Profissional especializado em alimentação e dietas" },
    { id: 223, word: "VETERINARIO", hint: "Profissional que cuida da saúde dos animais" },
    { id: 224, word: "ARQUITETO", hint: "Profissional que projeta edifícios e espaços" },
    { id: 225, word: "URBANISMO", hint: "Estudo do planejamento das cidades" },
    { id: 226, word: "TOPOGRAFIA", hint: "Estudo e representação do relevo de um terreno" },
    { id: 227, word: "CARTOGRAFIA", hint: "Ciência de criar mapas" },
    { id: 228, word: "METEOROLOGIA", hint: "Estudo do clima e das condições atmosféricas" },
    { id: 229, word: "OCEANOGRAFIA", hint: "Estudo científico dos oceanos" },
    { id: 230, word: "VULCANOLOGIA", hint: "Estudo científico dos vulcões" },
    { id: 231, word: "SISMOLOGIA", hint: "Estudo científico dos terremotos" },
    { id: 232, word: "PALEONTOLOGIA", hint: "Estudo científico de fósseis e vida pré-histórica" },
    { id: 233, word: "ANTROPOLOGIA", hint: "Estudo do ser humano e suas culturas" },
    { id: 234, word: "LINGUISTICA", hint: "Estudo científico da linguagem" },
    { id: 235, word: "ETIMOLOGIA", hint: "Estudo da origem das palavras" },
    { id: 236, word: "CALIGRAFIA", hint: "Arte de escrever com letras bonitas e elaboradas" },
    { id: 237, word: "TIPOGRAFIA", hint: "Arte e técnica de desenhar e organizar tipos de letras" },
    { id: 238, word: "CENOGRAFIA", hint: "Arte de criar cenários para peças, filmes ou eventos" },
    { id: 239, word: "COREOGRAFIA", hint: "Arte de compor sequências de movimentos de dança" },
    { id: 240, word: "DRAMATURGIA", hint: "Arte de escrever textos para teatro" },
    { id: 241, word: "ORQUESTRA", hint: "Grande grupo de músicos que tocam instrumentos variados juntos" },
    { id: 242, word: "SINFONIA", hint: "Composição musical extensa para orquestra" },
    { id: 243, word: "IDIOSSINCRASIA", hint: "Característica peculiar e própria de uma pessoa" },
    { id: 244, word: "EFEMERO", hint: "Que dura muito pouco tempo, passageiro" },
    { id: 245, word: "PERENE", hint: "Que dura para sempre ou por muito tempo" },
    { id: 246, word: "UBIQUO", hint: "Que está presente em todos os lugares ao mesmo tempo" },
    { id: 247, word: "INTRINSECO", hint: "Que é próprio de algo, essencial, não vindo de fora" },
    { id: 248, word: "EXTRINSECO", hint: "Que vem de fora, não é próprio de algo" },
    { id: 249, word: "PLETORA", hint: "Grande quantidade excessiva de algo" },
    { id: 250, word: "IDIOMA", hint: "Sistema de comunicação verbal de um povo ou nação" },
    { id: 251, word: "DIALETO", hint: "Variação regional de um idioma" },
    { id: 252, word: "NEOLOGISMO", hint: "Palavra ou expressão recém-criada em um idioma" },
    { id: 253, word: "ANACRONISMO", hint: "Algo fora do seu tempo histórico correto" },
    { id: 254, word: "PROTAGONISTA", hint: "Personagem principal de uma história" },
    { id: 255, word: "ANTAGONISTA", hint: "Personagem que se opõe ao protagonista" },
    { id: 256, word: "ALEGORIA", hint: "Representação simbólica de uma ideia através de outra" },
    { id: 257, word: "HIPERBOLE", hint: "Figura de linguagem que exagera intencionalmente" },
    { id: 258, word: "EUFEMISMO", hint: "Uso de palavras mais suaves para dizer algo desagradável" },
    { id: 259, word: "ONOMATOPEIA", hint: "Palavra que imita um som, como 'tique-taque'" },
    { id: 260, word: "PLEONASMO", hint: "Repetição desnecessária de uma ideia já expressa" },
    { id: 261, word: "POLISSEMIA", hint: "Qualidade de uma palavra ter vários significados" },
    { id: 262, word: "SINESTESIA", hint: "Figura de linguagem que mistura diferentes sentidos, como 'cor quente'" },
    { id: 263, word: "COSMOPOLITA", hint: "Relativo a alguém ou algo influenciado por várias culturas do mundo" },
    { id: 264, word: "XENOFOBIA", hint: "Aversão ou medo de pessoas estrangeiras" },
    { id: 265, word: "MERITOCRACIA", hint: "Sistema em que o mérito determina o sucesso de alguém" },
    { id: 266, word: "PLUTOCRACIA", hint: "Governo exercido pelos mais ricos" },
    { id: 267, word: "TECNOCRACIA", hint: "Governo exercido por especialistas técnicos" },
    { id: 268, word: "HEGEMONIA", hint: "Domínio ou liderança de um grupo sobre outros" },
    { id: 269, word: "IDEOLOGIA", hint: "Conjunto de ideias e valores que orientam um grupo ou pessoa" },
    { id: 270, word: "DICOTOMIA", hint: "Divisão entre duas partes opostas e complementares" },
    { id: 271, word: "SUBJETIVIDADE", hint: "Qualidade do que depende do ponto de vista pessoal" },
    { id: 272, word: "OBJETIVIDADE", hint: "Qualidade do que é imparcial, baseado em fatos" },
    { id: 273, word: "EPISTEMOLOGIA", hint: "Ramo da filosofia que estuda a natureza do conhecimento" },
    { id: 274, word: "METAFISICA", hint: "Ramo da filosofia que estuda a realidade além do mundo físico" },
    { id: 275, word: "EXISTENCIALISMO", hint: "Corrente filosófica que valoriza a existência e a liberdade individual" },
    { id: 276, word: "RACIOCINIO", hint: "Processo mental de pensar de forma lógica" },
    { id: 277, word: "INTUICAO", hint: "Capacidade de compreender algo sem raciocínio lógico explícito" },
    { id: 278, word: "PERSPICACIA", hint: "Capacidade de perceber coisas com rapidez e clareza" },
    { id: 279, word: "SAGACIDADE", hint: "Inteligência aguçada, esperteza" },
    { id: 280, word: "PROCRASTINACAO", hint: "Hábito de adiar tarefas" },
    { id: 281, word: "RESILIENCIA", hint: "Capacidade de se recuperar de dificuldades" },
    { id: 282, word: "EMPATIA", hint: "Capacidade de se colocar no lugar do outro" },
    { id: 283, word: "ALTRUISMO", hint: "Comportamento de ajudar os outros sem esperar recompensa" },
    { id: 284, word: "NARCISISMO", hint: "Excesso de admiração por si mesmo" },
    { id: 285, word: "MEGALOMANIA", hint: "Ideia exagerada sobre a própria importância ou poder" },
    { id: 286, word: "CLAUSTROFOBIA", hint: "Medo de espaços fechados" },
    { id: 287, word: "ACROFOBIA", hint: "Medo de altura" },
    { id: 288, word: "AGORAFOBIA", hint: "Medo de espaços abertos ou multidões" },
    { id: 289, word: "INSONIA", hint: "Dificuldade persistente para dormir" },
    { id: 290, word: "AMNESIA", hint: "Perda parcial ou total da memória" },
    { id: 291, word: "HIPOCONDRIA", hint: "Preocupação excessiva e infundada com a própria saúde" },
    { id: 292, word: "CATARSE", hint: "Libertação emocional intensa, muitas vezes através da arte" },
    { id: 293, word: "EFERVESCENTE", hint: "Que libera bolhas de gás; também usado para algo muito animado" },
    { id: 294, word: "INCANDESCENTE", hint: "Que brilha intensamente por causa do calor" },
    { id: 295, word: "LUMINESCENCIA", hint: "Emissão de luz sem produção de muito calor" },
    { id: 296, word: "FLUORESCENCIA", hint: "Emissão de luz quando exposto à radiação" },
    { id: 297, word: "METAMORFOSE", hint: "Transformação completa de forma, como a de lagarta em borboleta" },
    { id: 298, word: "CAMUFLAGEM", hint: "Técnica de se misturar ao ambiente para não ser percebido" },
    { id: 299, word: "HIBERNACAO", hint: "Estado de inatividade de certos animais durante o inverno" },
    { id: 300, word: "MIGRACAO", hint: "Deslocamento de pessoas ou animais de um lugar para outro" },
    { id: 301, word: "DOMESTICACAO", hint: "Processo de adaptar animais selvagens à convivência humana" }
  ];
})();
